$schema: "http://json-schema.org/draft-04/schema#"

id: "project"
title: Project
type: object
program: '*'
project: '*'
category: administrative
description: >
  Any specifically defined piece of work that is undertaken or attempted to meet a single
  requirement. (NCIt C47885)
additionalProperties: false
submittable: true
validators: null

systemProperties:
  - id
  - state
  - released
  - releasable
  - intended_release_date

required:
  - code
  - name
  - programs

uniqueKeys:
  - [ id ]
  - [ code ]

links:
  - name: programs
    backref: projects
    label: member_of
    target_type: program
    multiplicity: many_to_one
    required: true

constraints: null

properties:

  code:
    type: string
    description: "Unique identifier for the project."

  id:
    $ref: "_definitions.yaml#/UUID"
    systemAlias: node_id
    description: "UUID for the project." # TOREVIEW

  name:
    type: string
    description: "Display name/brief description for the project." # TOREVIEW

  type:
    type: string

  programs:
    $ref: "_definitions.yaml#/to_one"
    description: >
      The program to which the project belongs.
